version: '2'
services:
  fluentd-client-board:
    build: ./fluentd-client
    volumes:
      - ./fluentd-client/conf:/fluentd/etc    # fluentd.conf 파일을 컨테이너로 마운트  
      - /home/ubuntu/logging/board:/var/log  # 쌓인 서비스의 로그파일을 컨테이너로 마운트
    links:
      - "fluentd-aggregator"
    ports:
      - "25000:25000"
  
  fluentd-client-user:
    build: ./fluentd-client
    volumes:
      - ./fluentd-client/conf:/fluentd/etc  # fluentd.conf 파일을 컨테이너로 마운트  
      - /home/ubuntu/logging/user:/var/log  # 쌓인 서비스의 로그파일을 컨테이너로 마운트
    links:
      - "fluentd-aggregator"
    ports:
      - "25001:25000"

  fluentd-client-interest:
    build: ./fluentd-client
    volumes:
      - ./fluentd-client/conf:/fluentd/etc    
      - /home/ubuntu/logging/interest:/var/log  
    links:
      - "fluentd-aggregator"
    ports:
      - "25002:25000"

  fluentd-client-consumer:
    build: ./fluentd-client
    volumes:
      - ./fluentd-client/conf:/fluentd/etc
      - /home/ubuntu/logging/consumer:/var/log  
    links:
      - "fluentd-aggregator"
    ports:
      - "25003:25000"

  fluentd-aggregator:
    build: ./fluentd-aggregator
    volumes:
      - ./fluentd-aggregator/conf:/fluentd/etc # 로컬의 fluentd.conf 파일을 컨테이너로 마운트
    # links:
    #   - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

networks:
  internal:
    driver: bridge